pipeline {

  environment {
    dockerimagename = "neeraj91/react-app"
    dockerImage = ""
  }
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git 'https://github.com/neerajddun/jenkins-pipeline.git'
      }
    }
    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }
    stage('Pushing Image') {
      environment {
          registryCredential = 'dockerhub-credentials'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }
    stage('Deploy to Kubernetes') {
  steps {
    withCredentials([file(credentialsId: 'kube-credentials',variable: 'KUBECONFIG')]) {
      sh "kubectl apply -f jenkins-deploy/deployment.yaml"
      sh "kubectl apply -f jenkins-deploy/service.yaml"
    }
  }
}
  }
}